### ISSUE TITLE
Yank v0.4.2 from pypi

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stac-api-validator#243]
Because of https://github.com/stac-utils/stac-api-validator/issues/240, existing workflows that rely on **stac-api-validator** might break, even if they're still valid STAC API. What do we think about yanking [v0.4.2](https://pypi.org/project/stac-api-validator/0.4.2/) from PyPI?

**Comment by philvarner** [comment]
Releasing 0.4.3 imminently!
