### ISSUE TITLE
Remove invalid example of RFC3339 datetime that uses comma as the fractional seconds separator

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-api-validator#35]
Remove invalid example of RFC3339 datetime that uses comma as the fractional seconds separator, as this is only allowed in ISO8601 and not RFC 3339

**Comment by alainbodiguel** [comment]
as per https://datatracker.ietf.org/doc/html/rfc3339#section-5.6

**Comment by philvarner** [comment]
resolved in a856d698559ecb8ad530c898545af5be71bce3f7
