### ISSUE TITLE
item-search does not imply support for collections?

### ISSUE THREAD

**Issue by srepmub** [stac-utils/stac-api-validator#36]
before I forgot, thanks for this tool. it's very helpful!!

I'm trying to validate a landing page which advertises just these two conformance classes:

https://api.stacspec.org/v1.0.0-beta.2/core
https://api.stacspec.org/v1.0.0-beta.2/item-search

stac-api-validator seems to assume that this also implies support for /collections (or rel data), even though we haven't advertised this.. would this really be implied, or is stac-api-validator assuming too much?

what I'm trying to do is to have a separate landing page for each collection (in addition to the dataset landing page). I agree this may be a bit weird.

**Comment by philvarner** [comment]
SAV is assuming too much. Most implementations support ogcapi-features or collections, and I wasn't thinking about the fact that this would be required to do the collections query parameter tests. I'll look into making that more modular.

**Comment by philvarner** [comment]
Over a year later, and I finally go around to fixing this. Thanks for pointing it out -- this is something I'm going to be more careful about going forward.

**Comment by srepmub** [comment]
great to hear, thanks for fixing! :-)
