### ISSUE TITLE
service-desc error for Content-Type having extra space

### ISSUE THREAD

**Issue by afasseco** [stac-utils/stac-api-validator#40]
Hi

Great work with this validator. We've been running the ogccite/ets-ogcapi-features10 test suite on our OGC API Features APIs and we're looking to include this on our STAC APIs as well.

One error that we're stuck on is:

Validating http://localhost:8085/url
STAC API - Core conformance class found.
warnings: none
errors:
- service-desc ({'href': 'http://localhost:8085/url/api', 'rel': 'service-desc', 'type': 'application/vnd.oai.openapi+json;version=3.0', 'title': 'the API definition '}): should have content-type header 'application/vnd.oai.openapi+json;version=3.0'', actually 'application/vnd.oai.openapi+json; version=3.0'

If I read this correctly, its because the returned content-type has an extra space just before the version. And the spec (https://github.com/radiantearth/stac-api-spec/tree/master/core#endpoints) says without spaces, so that checks out. This content-type is accepted by the ogccite/ets-ogcapi-features10 test suite however.

I do not have a space in the content-type I set in our service implementation so its probably being set in our http library (spring boot / tomcat) somewhere (https://bz.apache.org/bugzilla/show_bug.cgi?id=62912 seems likely). https://datatracker.ietf.org/doc/html/rfc7231#section-3.1 looks like space is ok, although no space is preferred.

Code that does the comparison is here: https://github.com/stac-utils/stac-api-validator/blob/afb5a91ed6ce804d6b33fb304d6532dd4c50a227/stac_api_validator/validations.py#L190

So what I'm asking; should the extra space be accepted in the content-type between the type and the parameters?

**Comment by philvarner** [comment]
Looks whitespace is allowed:

`media-type = type "/" subtype *( OWS ";" OWS parameter )`

where OWS == Optional Whitespace

I'll keep that in mind as we check types going forward. For this particular check, the behavior has been changed so that instead of checking the type matches that exact string, it checks that the type value advertised is the same as returned by invoking the endpoint.

**Comment by philvarner** [comment]
@afasseco I think I fixed this. If it doesn't work as expected, please let me know.

**Comment by afasseco** [comment]
@philvarner thanks for the kind reminder.

I've rerun this on our service and it no longer gives this error. So its fixed.

This issue can be closed.
