### ISSUE TITLE
Python error when checking /conformance endpoint

### ISSUE THREAD

**Issue by jjrom** [stac-utils/stac-api-validator#83]
Checking conformance features on https://tamn.snapplanet.io

stac-api-validator --root-url https://tamn.snapplanet.io --conformance features --no-post --log-level DEBUG
Validating https://tamn.snapplanet.io
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): tamn.snapplanet.io:443
DEBUG:urllib3.connectionpool:https://tamn.snapplanet.io:443 "GET / HTTP/1.1" 200 None
Validating STAC API - Core conformance class.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): tamn.snapplanet.io:443
DEBUG:urllib3.connectionpool:https://tamn.snapplanet.io:443 "GET /api HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): tamn.snapplanet.io:443
DEBUG:urllib3.connectionpool:https://tamn.snapplanet.io:443 "GET /api.html HTTP/1.1" 200 None
Validating STAC API - Features conformance class.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): tamn.snapplanet.io:443
DEBUG:urllib3.connectionpool:https://tamn.snapplanet.io:443 "GET /conformance HTTP/1.1" 200 None
Failed.
Error https://tamn.snapplanet.io: <class 'AttributeError'> 'tuple' object has no attribute 'split'
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/stac_api_validator/__main__.py", line 57, in main
    (warnings, errors) = validate_api(root_url, post, conformance_classes)
  File "/opt/homebrew/lib/python3.10/site-packages/stac_api_validator/validations.py", line 215, in validate_api
    validate_features(root_body, conforms_to, warnings, errors)
  File "/opt/homebrew/lib/python3.10/site-packages/stac_api_validator/validations.py", line 367, in validate_features
    if (ct := r_conformance.headers.get("content-type"), "").split(";")[
AttributeError: 'tuple' object has no attribute 'split'

The error seems to be related to https://tamn.snapplanet.io/conformance endpoint. However this endpoint exists and seems valid.

**Comment by philvarner** [comment]
IIRC, this was caused by a stray comma at the end of a line, which made a string into a 1-tuple. Works correctly with current main branch.

**Comment by philvarner** [comment]
fixed in <https://github.com/stac-utils/stac-api-validator/releases/tag/v0.0.3>
